export const order_constants = {
  ORDER_CREATE: "ORDER_CREATE_REQUEST",
  ORDER_CREATE_SUCCESS: "ORDER_CREATE_REQUEST_SUCCESS",
  ORDER_CREATE_FAILED: "ORDER_CREATE_REQUEST_FAILED",
  ORDER_RESET: "ORDER_RESET_REQUEST",
  ORDER_DETAIL: "ORDER_DETAIL_REQUEST",
  ORDER_DETAIL_SUCCESS: "ORDER_DETAIL_REQUEST_SUCCESS",
  ORDER_DETAIL_FAILED: "ORDER_DETAIL_REQUEST_FAILED",
  ORDER_PAY: "ORDER_PAY_REQUEST",
  ORDER_PAY_SUCCESS: "ORDER_PAY_REQUEST_SUCCESS",
  ORDER_PAY_FAILED: "ORDER_PAY_REQUEST_FAILED",
  ORDER_PAY_RESET: "ORDER_PAY_RESET_REQUEST",
  ORDER_LIST_PURCHASES: "ORDER_LIST_PURCHASES_REQUEST",
  ORDER_LIST_PURCHASES_SUCCESS: "ORDER_LIST_PURCHASES_REQUEST_SUCCESS",
  ORDER_LIST_PURCHASES_FAILED: "ORDER_LIST_PURCHASES_REQUEST_FAILED",
  ORDER_LIST_PURCHASES_RESET: "ORDER_LIST_PURCHASES_REQUEST_RESET",
  ORDER_ADMIN_LIST_ORDERS: "ORDER_ADMIN_LIST_ORDERS_REQUEST",
  ORDER_ADMIN_LIST_ORDERS_SUCCESS: "ORDER_ADMIN_LIST_ORDERS_REQUEST_SUCCESS",
  ORDER_ADMIN_LIST_ORDERS_FAILED: "ORDER_ADMIN_LIST_ORDERS_REQUEST_FAILED",
  ORDER_ADMIN_LIST_ORDERS_RESET: "ORDER_ADMIN_LIST_ORDERS_REQUEST_RESET",
  ORDER_ADMIN_SET_ORDER_DELIVERED: "ORDER_ADMIN_SET_ORDER_DELIVERED_REQUEST",
  ORDER_ADMIN_SET_ORDER_DELIVERED_SUCCESS:
    "ORDER_ADMIN_SET_ORDER_DELIVERED_REQUEST_SUCCESS",
  ORDER_ADMIN_SET_ORDER_DELIVERED_FAILED:
    "ORDER_ADMIN_SET_ORDER_DELIVERED_REQUEST_FAILED",
  ORDER_ADMIN_SET_ORDER_DELIVERED_RESET:
    "ORDER_ADMIN_SET_ORDER_DELIVERED_RESET_REQUEST",

  ORDER_ADMIN_DELETE_ORDER: "ORDER_ADMIN_DELETE_ORDER_REQUEST",
  ORDER_ADMIN_DELETE_ORDER_SUCCESS: "ORDER_ADMIN_DELETE_ORDER_REQUEST_SUCCESS",
  ORDER_ADMIN_DELETE_ORDER_FAILED: "ORDER_ADMIN_DELETE_ORDER_REQUEST_FAILED",
};
